import { useState, useEffect } from "react";
import { TASK_CATEGORIES, TASK_PRIORITIES, RECURRING_OPTIONS } from "../lib/constants.js";
import { fmt, getAnimalName, daysUntil, daysUntilDue, fmtDueRange, getCanonicalPastureNames } from "../lib/helpers.js";
import { sanitizeDate, todayLocalISODate } from "../lib/dateUtils.js";
import { Card, Btn, Input, Select, SectionTitle, Textarea, Badge } from "./ui.jsx";
import DateInputWithValidation from "./DateInputWithValidation.jsx";

export default function Tasks({ tasks, setTasks, animals, gestations, offspring, pastures, setTab }) {
  const [showAdd, setShowAdd] = useState(false);
  const todayStr = todayLocalISODate();
  const [form, setForm] = useState({
    name: "",
    dueDate: todayStr,
    dueTime: "",
    category: "General",
    priority: "Medium",
    animalId: "",
    pastureName: "",
    notes: "",
    recurring: "One time",
  });

  useEffect(() => {
    if (!setTasks || !animals) return;
    const existingSourceIds = new Set((tasks || []).filter(t => t.sourceId).map(t => t.sourceId));
    const toAdd = [];
    (animals || []).forEach(a => {
      (a.vaccinations || []).forEach(v => {
        const nextDue = v.nextDueDate || v.dateGiven;
        if (!nextDue) return;
        const dueSan = sanitizeDate(nextDue);
        if (!dueSan) return;
        const d = daysUntil(dueSan);
        if (d < 0 || d > 7) return;
        const sourceId = `vaccination-${a.id}-${v.id}`;
        if (existingSourceIds.has(sourceId)) return;
        toAdd.push({
          id: `auto-${sourceId}-${Date.now()}`,
          name: `Vaccination due: ${(v.vaccineName || "Vaccine")} — ${getAnimalName(a)}`,
          dueDate: dueSan,
          category: "Vaccination",
          priority: "Medium",
          animalId: a.id,
          sourceId,
          autoGenerated: true,
        });
        existingSourceIds.add(sourceId);
      });
    });
    Object.values(offspring || {}).forEach(list => {
      (list || []).forEach(c => {
        if (!c.weaningDate) return;
        const weanSan = sanitizeDate(c.weaningDate);
        if (!weanSan) return;
        const d = daysUntil(weanSan);
        if (d < 0 || d > 7) return;
        const sourceId = `weaning-${c.id || c.name || Math.random()}`;
        if (existingSourceIds.has(sourceId)) return;
        toAdd.push({
          id: `auto-${sourceId}-${Date.now()}`,
          name: `Weaning due: ${c.name || "Offspring"}`,
          dueDate: weanSan,
          category: "Weaning",
          priority: "Medium",
          sourceId,
          autoGenerated: true,
        });
        existingSourceIds.add(sourceId);
      });
    });
    if (toAdd.length > 0) setTasks(prev => [...(prev || []), ...toAdd]);
  }, [setTasks, animals, offspring, tasks]);

  const allTasks = (tasks || []).filter(t => !t.completed);
  const completedTasks = (tasks || []).filter(t => t.completed);
  const todayTasks = allTasks.filter(t => t.dueDate === todayStr);
  const overdueTasks = allTasks.filter(t => t.dueDate && t.dueDate < todayStr);
  const upcomingTasks = allTasks.filter(t => t.dueDate && t.dueDate > todayStr).sort((a, b) => (a.dueDate || "").localeCompare(b.dueDate || ""));

  const activeGestations = (gestations || []).filter(g => g.status !== "Delivered");
  const gestationTaskItems = activeGestations.map(g => {
    const animal = (animals || []).find(a => a.id === g.animalId);
    const dueD = daysUntilDue(g);
    const isOverdue = dueD.isRange ? dueD.end < 0 : dueD.start < 0;
    const isDueNow = dueD.isRange ? (dueD.start <= 0 && dueD.end >= 0) : dueD.start === 0;
    const status = isOverdue ? "overdue" : isDueNow ? "dueNow" : "upcoming";
    const dueDateForSort = g.dueDateStart || g.dueDate;
    return { type: "gestation", id: `gestation-${g.id}`, g, animal, dueD, status, dueDateForSort, name: `Gestation due: ${getAnimalName(animal) || "Animal"}` };
  });
  const gestationOverdue = gestationTaskItems.filter(i => i.status === "overdue");
  const gestationDueNow = gestationTaskItems.filter(i => i.status === "dueNow");
  const gestationUpcoming = gestationTaskItems.filter(i => i.status === "upcoming").sort((a, b) => (a.dueD.start - b.dueD.start));

  function addTask() {
    const dueSan = sanitizeDate(form.dueDate);
    if (!form.name?.trim() || !dueSan) return;
    setTasks(prev => [...(prev || []), {
      id: Date.now().toString(),
      name: form.name.trim(),
      dueDate: dueSan,
      dueTime: (form.dueTime || "").trim() || undefined,
      category: form.category || "General",
      priority: form.priority || "Medium",
      animalId: (form.animalId || "").trim() || undefined,
      pastureName: (form.pastureName || "").trim() || undefined,
      notes: (form.notes || "").trim() || undefined,
      recurring: form.recurring || "One time",
    }]);
    setForm({ name: "", dueDate: todayStr, dueTime: "", category: "General", priority: "Medium", animalId: "", pastureName: "", notes: "", recurring: "One time" });
    setShowAdd(false);
  }

  function toggleComplete(task) {
    setTasks(prev => prev.map(t => t.id === task.id ? { ...t, completed: !t.completed, completedAt: !t.completed ? new Date().toISOString() : undefined } : t));
  }

  function deleteTask(id) {
    if (!confirm("Delete this task?")) return;
    setTasks(prev => prev.filter(t => t.id !== id));
  }

  const priorityColor = { High: "var(--danger2)", Medium: "var(--brass)", Low: "var(--green3)" };
  const pastureNames = getCanonicalPastureNames(animals, pastures);

  function renderTaskRow(task, rowHighlight) {
    const animal = task.animalId ? (animals || []).find(a => a.id === task.animalId) : null;
    return (
      <div key={task.id} style={{ display: "flex", alignItems: "center", gap: "10px", padding: "12px 14px", background: rowHighlight?.background || "#fff", border: "1px solid var(--cream3)", borderRadius: "var(--radius)", borderLeft: `4px solid ${priorityColor[task.priority] || "var(--green3)"}`, color: rowHighlight?.color }}>
        <input type="checkbox" checked={!!task.completed} onChange={() => toggleComplete(task)} style={{ width: "18px", height: "18px", accentColor: "var(--green)", flexShrink: 0 }} />
        <div style={{ width: "10px", height: "10px", borderRadius: "50%", background: priorityColor[task.priority] || "var(--green3)", flexShrink: 0 }} title={task.priority} />
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontWeight: 600, fontSize: "14px" }}>{task.name}</div>
          <div style={{ fontSize: "12px", color: rowHighlight?.color || "var(--muted)", marginTop: "2px" }}>
            {task.dueDate ? fmt(task.dueDate) : ""}{task.dueTime ? ` ${task.dueTime}` : ""}
            {task.category && ` · ${task.category}`}
            {animal && ` · ${getAnimalName(animal)}`}
            {task.pastureName && ` · ${task.pastureName}`}
          </div>
        </div>
        <Btn size="sm" variant="ghost" onClick={() => deleteTask(task.id)} style={{ padding: "4px 8px", minWidth: 0 }}>×</Btn>
      </div>
    );
  }

  function renderGestationRow(item, rowHighlight) {
    const { g, animal, dueD } = item;
    const badge = item.status === "overdue" ? <Badge color="var(--danger2)">OVERDUE</Badge> : item.status === "dueNow" ? <Badge color="var(--brass2)">DUE NOW</Badge> : null;
    return (
      <div key={item.id} style={{ display: "flex", alignItems: "center", gap: "10px", padding: "12px 14px", background: rowHighlight?.background || "#fff", border: "1px solid var(--cream3)", borderRadius: "var(--radius)", borderLeft: `4px solid ${item.status === "overdue" ? "var(--danger2)" : item.status === "dueNow" ? "var(--brass2)" : "var(--green3)"}`, color: rowHighlight?.color }}>
        <div style={{ width: "18px", flexShrink: 0 }} />
        <div style={{ width: "10px", height: "10px", borderRadius: "50%", background: item.status === "overdue" ? "var(--danger2)" : item.status === "dueNow" ? "var(--brass2)" : "var(--green3)", flexShrink: 0 }} />
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontWeight: 600, fontSize: "14px", display: "flex", alignItems: "center", flexWrap: "wrap", gap: "8px" }}>{item.name}{badge}</div>
          <div style={{ fontSize: "12px", color: rowHighlight?.color || "var(--muted)", marginTop: "2px" }}>
            Due {fmtDueRange(g)}
            {animal?.species && ` · ${animal.species}`}
          </div>
        </div>
      </div>
    );
  }

  function renderTaskList(list, title, titleColor, rowHighlight) {
    if (list.length === 0) return null;
    return (
      <div style={{ marginBottom: "20px" }}>
        <div style={{ fontSize: "12px", fontWeight: 600, color: titleColor || "var(--muted)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "8px" }}>{title}</div>
        <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
          {list.map(t => renderTaskRow(t, rowHighlight))}
        </div>
      </div>
    );
  }

  const combinedOverdue = [...overdueTasks, ...gestationOverdue];
  const combinedUpcoming = [...upcomingTasks, ...gestationUpcoming].sort((a, b) => {
    const dateA = a.type === "gestation" ? a.dueDateForSort : a.dueDate;
    const dateB = b.type === "gestation" ? b.dueDateForSort : b.dueDate;
    const cmp = (dateA || "").localeCompare(dateB || "");
    if (cmp !== 0) return cmp;
    if (a.type === "gestation" && b.type === "gestation") return (a.dueD?.start ?? 0) - (b.dueD?.start ?? 0);
    return 0;
  });

  function renderMixedList(list, title, titleColor, rowHighlight) {
    if (list.length === 0) return null;
    return (
      <div style={{ marginBottom: "20px" }}>
        <div style={{ fontSize: "12px", fontWeight: 600, color: titleColor || "var(--muted)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "8px" }}>{title}</div>
        <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
          {list.map(item => item.type === "gestation" ? renderGestationRow(item, rowHighlight) : renderTaskRow(item, rowHighlight))}
        </div>
      </div>
    );
  }

  return (
    <div className="hl-page hl-fade-in">
      <SectionTitle action={<Btn onClick={() => setShowAdd(true)}>+ Add Task</Btn>}>
        Tasks
      </SectionTitle>

      {showAdd && (
        <Card style={{ padding: "24px", marginBottom: "24px", borderLeft: "4px solid var(--green3)" }}>
          <div style={{ fontFamily: "'Playfair Display'", fontSize: "18px", fontWeight: 600, marginBottom: "18px" }}>Add Task</div>
          <div className="hl-form-grid-3" style={{ marginBottom: "14px" }}>
            <Input label="Task name *" value={form.name} onChange={e => setForm(p => ({ ...p, name: e.target.value }))} placeholder="e.g. Feed hay" />
            <DateInputWithValidation label="Due date *" breedingDueTwoDigitYear value={form.dueDate} onValueChange={v => setForm(p => ({ ...p, dueDate: v }))} />
            <Input label="Due time (optional)" type="time" value={form.dueTime} onChange={e => setForm(p => ({ ...p, dueTime: e.target.value }))} />
            <Select label="Category" value={form.category} onChange={e => setForm(p => ({ ...p, category: e.target.value }))}>
              {TASK_CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
            </Select>
            <Select label="Priority" value={form.priority} onChange={e => setForm(p => ({ ...p, priority: e.target.value }))}>
              {TASK_PRIORITIES.map(p => <option key={p} value={p}>{p}</option>)}
            </Select>
            <Select label="Assign to animal (optional)" value={form.animalId} onChange={e => setForm(p => ({ ...p, animalId: e.target.value }))}>
              <option value="">— None —</option>
              {(animals || []).map(a => <option key={a.id} value={a.id}>{getAnimalName(a)}{a.tag ? ` #${a.tag}` : ""}</option>)}
            </Select>
            <Select label="Assign to pasture (optional)" value={form.pastureName} onChange={e => setForm(p => ({ ...p, pastureName: e.target.value }))}>
              <option value="">— None —</option>
              {pastureNames.map(n => <option key={n} value={n}>{n}</option>)}
            </Select>
            <Select label="Recurring" value={form.recurring} onChange={e => setForm(p => ({ ...p, recurring: e.target.value }))}>
              {RECURRING_OPTIONS.map(r => <option key={r} value={r}>{r}</option>)}
            </Select>
          </div>
          <Textarea label="Notes" value={form.notes} onChange={e => setForm(p => ({ ...p, notes: e.target.value }))} rows={2} style={{ marginBottom: "14px" }} placeholder="Optional" />
          <div className="hl-card-actions" style={{ display: "flex", gap: "10px" }}>
            <Btn onClick={addTask}>Save Task</Btn>
            <Btn variant="secondary" onClick={() => setShowAdd(false)}>Cancel</Btn>
          </div>
        </Card>
      )}

      {renderMixedList(combinedOverdue, "Overdue", "var(--danger2)", { color: "var(--danger2)", background: "rgba(180, 60, 50, 0.08)" })}
      {gestationDueNow.length > 0 && renderMixedList(gestationDueNow, "Due Now", "var(--brass2)", { color: "var(--brass2)", background: "rgba(201, 149, 42, 0.08)" })}
      {renderTaskList(todayTasks, "Today")}
      {renderMixedList(combinedUpcoming, "Upcoming")}

      {completedTasks.length > 0 && (
        <div style={{ marginTop: "24px", paddingTop: "20px", borderTop: "1px solid var(--cream2)" }}>
          <div style={{ fontSize: "12px", fontWeight: 600, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "8px" }}>Done</div>
          <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
            {completedTasks.sort((a, b) => (b.completedAt || "").localeCompare(a.completedAt || "")).map(t => {
              const animal = t.animalId ? (animals || []).find(a => a.id === t.animalId) : null;
              return (
                <div key={t.id} style={{ display: "flex", alignItems: "center", gap: "10px", padding: "10px 14px", background: "var(--cream)", border: "1px solid var(--cream2)", borderRadius: "var(--radius)", opacity: 0.85 }}>
                  <input type="checkbox" checked onChange={() => toggleComplete(t)} style={{ width: "18px", height: "18px", accentColor: "var(--green)", flexShrink: 0 }} />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontWeight: 500, fontSize: "14px", textDecoration: "line-through", color: "var(--muted)" }}>{t.name}</div>
                    <div style={{ fontSize: "12px", color: "var(--muted)", marginTop: "2px" }}>{t.dueDate ? fmt(t.dueDate) : ""}{animal && ` · ${getAnimalName(animal)}`}</div>
                  </div>
                  <Btn size="sm" variant="ghost" onClick={() => deleteTask(t.id)} style={{ padding: "4px 8px", minWidth: 0 }}>×</Btn>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {!showAdd && (tasks || []).length === 0 && activeGestations.length === 0 && (
        <Card style={{ padding: "60px", textAlign: "center" }}>
          <div style={{ fontSize: "40px", marginBottom: "10px" }}>✓</div>
          <div style={{ color: "var(--muted)", fontSize: "15px" }}>No tasks yet.</div>
          <p style={{ fontSize: "13px", color: "var(--muted)", marginTop: "8px" }}>Add a task or open the Tasks tab — gestation, vaccination, and weaning due soon will appear here automatically.</p>
        </Card>
      )}
    </div>
  );
}
