import { useState, useEffect } from "react";
import { TASK_CATEGORIES, TASK_PRIORITIES, RECURRING_OPTIONS } from "../lib/constants.js";
import { fmt, getAnimalName, daysUntil, getCanonicalPastureNames } from "../lib/helpers.js";
import { Card, Btn, Input, Select, SectionTitle, Textarea } from "./ui.jsx";

export default function Tasks({ tasks, setTasks, animals, gestations, offspring, pastures, setTab }) {
  const [showAdd, setShowAdd] = useState(false);
  const todayStr = new Date().toISOString().split("T")[0];
  const [form, setForm] = useState({
    name: "",
    dueDate: todayStr,
    dueTime: "",
    category: "General",
    priority: "Medium",
    animalId: "",
    pastureName: "",
    notes: "",
    recurring: "One time",
  });

  useEffect(() => {
    if (!setTasks || !animals || !gestations) return;
    const existingSourceIds = new Set((tasks || []).filter(t => t.sourceId).map(t => t.sourceId));
    const toAdd = [];
    const activeGestations = (gestations || []).filter(g => g.status !== "Delivered");
    activeGestations.forEach(g => {
      const dueStr = g.dueDateStart || g.dueDate;
      if (!dueStr) return;
      const d = daysUntil(dueStr);
      if (d < 0 || d > 7) return;
      const sourceId = `gestation-${g.id}`;
      if (existingSourceIds.has(sourceId)) return;
      const animal = (animals || []).find(a => a.id === g.animalId);
      toAdd.push({
        id: `auto-${sourceId}-${Date.now()}`,
        name: `Gestation due: ${getAnimalName(animal) || "Animal"}`,
        dueDate: dueStr,
        category: "Breeding",
        priority: "High",
        sourceId,
        autoGenerated: true,
      });
      existingSourceIds.add(sourceId);
    });
    (animals || []).forEach(a => {
      (a.vaccinations || []).forEach(v => {
        const nextDue = v.nextDueDate || v.dateGiven;
        if (!nextDue) return;
        const d = daysUntil(nextDue);
        if (d < 0 || d > 7) return;
        const sourceId = `vaccination-${a.id}-${v.id}`;
        if (existingSourceIds.has(sourceId)) return;
        toAdd.push({
          id: `auto-${sourceId}-${Date.now()}`,
          name: `Vaccination due: ${(v.vaccineName || "Vaccine")} — ${getAnimalName(a)}`,
          dueDate: nextDue,
          category: "Vaccination",
          priority: "Medium",
          animalId: a.id,
          sourceId,
          autoGenerated: true,
        });
        existingSourceIds.add(sourceId);
      });
    });
    Object.values(offspring || {}).forEach(list => {
      (list || []).forEach(c => {
        if (!c.weaningDate) return;
        const d = daysUntil(c.weaningDate);
        if (d < 0 || d > 7) return;
        const sourceId = `weaning-${c.id || c.name || Math.random()}`;
        if (existingSourceIds.has(sourceId)) return;
        toAdd.push({
          id: `auto-${sourceId}-${Date.now()}`,
          name: `Weaning due: ${c.name || "Offspring"}`,
          dueDate: c.weaningDate,
          category: "Weaning",
          priority: "Medium",
          sourceId,
          autoGenerated: true,
        });
        existingSourceIds.add(sourceId);
      });
    });
    if (toAdd.length > 0) setTasks(prev => [...(prev || []), ...toAdd]);
  }, [setTasks, animals, gestations, offspring, tasks]);

  const allTasks = (tasks || []).filter(t => !t.completed);
  const completedTasks = (tasks || []).filter(t => t.completed);
  const todayTasks = allTasks.filter(t => t.dueDate === todayStr);
  const overdueTasks = allTasks.filter(t => t.dueDate && t.dueDate < todayStr);
  const upcomingTasks = allTasks.filter(t => t.dueDate && t.dueDate > todayStr).sort((a, b) => (a.dueDate || "").localeCompare(b.dueDate || ""));

  function addTask() {
    if (!form.name?.trim() || !form.dueDate) return;
    setTasks(prev => [...(prev || []), {
      id: Date.now().toString(),
      name: form.name.trim(),
      dueDate: form.dueDate,
      dueTime: (form.dueTime || "").trim() || undefined,
      category: form.category || "General",
      priority: form.priority || "Medium",
      animalId: (form.animalId || "").trim() || undefined,
      pastureName: (form.pastureName || "").trim() || undefined,
      notes: (form.notes || "").trim() || undefined,
      recurring: form.recurring || "One time",
    }]);
    setForm({ name: "", dueDate: todayStr, dueTime: "", category: "General", priority: "Medium", animalId: "", pastureName: "", notes: "", recurring: "One time" });
    setShowAdd(false);
  }

  function toggleComplete(task) {
    setTasks(prev => prev.map(t => t.id === task.id ? { ...t, completed: !t.completed, completedAt: !t.completed ? new Date().toISOString() : undefined } : t));
  }

  function deleteTask(id) {
    if (!confirm("Delete this task?")) return;
    setTasks(prev => prev.filter(t => t.id !== id));
  }

  const priorityColor = { High: "var(--danger2)", Medium: "var(--brass)", Low: "var(--green3)" };
  const pastureNames = getCanonicalPastureNames(animals, pastures);

  function renderTaskList(list, title, titleColor, rowHighlight) {
    if (list.length === 0) return null;
    return (
      <div style={{ marginBottom: "20px" }}>
        <div style={{ fontSize: "12px", fontWeight: 600, color: titleColor || "var(--muted)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "8px" }}>{title}</div>
        <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
          {list.map(t => {
            const animal = t.animalId ? (animals || []).find(a => a.id === t.animalId) : null;
            return (
              <div key={t.id} style={{ display: "flex", alignItems: "center", gap: "10px", padding: "12px 14px", background: rowHighlight?.background || "#fff", border: "1px solid var(--cream3)", borderRadius: "var(--radius)", borderLeft: `4px solid ${priorityColor[t.priority] || "var(--green3)"}`, color: rowHighlight?.color }}>
                <input type="checkbox" checked={!!t.completed} onChange={() => toggleComplete(t)} style={{ width: "18px", height: "18px", accentColor: "var(--green)", flexShrink: 0 }} />
                <div style={{ width: "10px", height: "10px", borderRadius: "50%", background: priorityColor[t.priority] || "var(--green3)", flexShrink: 0 }} title={t.priority} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontWeight: 600, fontSize: "14px" }}>{t.name}</div>
                  <div style={{ fontSize: "12px", color: rowHighlight?.color || "var(--muted)", marginTop: "2px" }}>
                    {t.dueDate ? fmt(t.dueDate) : ""}{t.dueTime ? ` ${t.dueTime}` : ""}
                    {t.category && ` · ${t.category}`}
                    {animal && ` · ${getAnimalName(animal)}`}
                    {t.pastureName && ` · ${t.pastureName}`}
                  </div>
                </div>
                <Btn size="sm" variant="ghost" onClick={() => deleteTask(t.id)} style={{ padding: "4px 8px", minWidth: 0 }}>×</Btn>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  return (
    <div className="hl-page hl-fade-in">
      <SectionTitle action={<Btn onClick={() => setShowAdd(true)}>+ Add Task</Btn>}>
        Tasks
      </SectionTitle>

      {showAdd && (
        <Card style={{ padding: "24px", marginBottom: "24px", borderLeft: "4px solid var(--green3)" }}>
          <div style={{ fontFamily: "'Playfair Display'", fontSize: "18px", fontWeight: 600, marginBottom: "18px" }}>Add Task</div>
          <div className="hl-form-grid-3" style={{ marginBottom: "14px" }}>
            <Input label="Task name *" value={form.name} onChange={e => setForm(p => ({ ...p, name: e.target.value }))} placeholder="e.g. Feed hay" />
            <Input label="Due date *" type="date" value={form.dueDate} onChange={e => setForm(p => ({ ...p, dueDate: e.target.value }))} />
            <Input label="Due time (optional)" type="time" value={form.dueTime} onChange={e => setForm(p => ({ ...p, dueTime: e.target.value }))} />
            <Select label="Category" value={form.category} onChange={e => setForm(p => ({ ...p, category: e.target.value }))}>
              {TASK_CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
            </Select>
            <Select label="Priority" value={form.priority} onChange={e => setForm(p => ({ ...p, priority: e.target.value }))}>
              {TASK_PRIORITIES.map(p => <option key={p} value={p}>{p}</option>)}
            </Select>
            <Select label="Assign to animal (optional)" value={form.animalId} onChange={e => setForm(p => ({ ...p, animalId: e.target.value }))}>
              <option value="">— None —</option>
              {(animals || []).map(a => <option key={a.id} value={a.id}>{getAnimalName(a)}{a.tag ? ` #${a.tag}` : ""}</option>)}
            </Select>
            <Select label="Assign to pasture (optional)" value={form.pastureName} onChange={e => setForm(p => ({ ...p, pastureName: e.target.value }))}>
              <option value="">— None —</option>
              {pastureNames.map(n => <option key={n} value={n}>{n}</option>)}
            </Select>
            <Select label="Recurring" value={form.recurring} onChange={e => setForm(p => ({ ...p, recurring: e.target.value }))}>
              {RECURRING_OPTIONS.map(r => <option key={r} value={r}>{r}</option>)}
            </Select>
          </div>
          <Textarea label="Notes" value={form.notes} onChange={e => setForm(p => ({ ...p, notes: e.target.value }))} rows={2} style={{ marginBottom: "14px" }} placeholder="Optional" />
          <div className="hl-card-actions" style={{ display: "flex", gap: "10px" }}>
            <Btn onClick={addTask}>Save Task</Btn>
            <Btn variant="secondary" onClick={() => setShowAdd(false)}>Cancel</Btn>
          </div>
        </Card>
      )}

      {renderTaskList(overdueTasks, "Overdue", "var(--danger2)", { color: "var(--danger2)", background: "rgba(180, 60, 50, 0.08)" })}
      {renderTaskList(todayTasks, "Today")}
      {renderTaskList(upcomingTasks, "Upcoming")}

      {completedTasks.length > 0 && (
        <div style={{ marginTop: "24px", paddingTop: "20px", borderTop: "1px solid var(--cream2)" }}>
          <div style={{ fontSize: "12px", fontWeight: 600, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "8px" }}>Done</div>
          <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
            {completedTasks.sort((a, b) => (b.completedAt || "").localeCompare(a.completedAt || "")).map(t => {
              const animal = t.animalId ? (animals || []).find(a => a.id === t.animalId) : null;
              return (
                <div key={t.id} style={{ display: "flex", alignItems: "center", gap: "10px", padding: "10px 14px", background: "var(--cream)", border: "1px solid var(--cream2)", borderRadius: "var(--radius)", opacity: 0.85 }}>
                  <input type="checkbox" checked onChange={() => toggleComplete(t)} style={{ width: "18px", height: "18px", accentColor: "var(--green)", flexShrink: 0 }} />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontWeight: 500, fontSize: "14px", textDecoration: "line-through", color: "var(--muted)" }}>{t.name}</div>
                    <div style={{ fontSize: "12px", color: "var(--muted)", marginTop: "2px" }}>{t.dueDate ? fmt(t.dueDate) : ""}{animal && ` · ${getAnimalName(animal)}`}</div>
                  </div>
                  <Btn size="sm" variant="ghost" onClick={() => deleteTask(t.id)} style={{ padding: "4px 8px", minWidth: 0 }}>×</Btn>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {!showAdd && (tasks || []).length === 0 && (
        <Card style={{ padding: "60px", textAlign: "center" }}>
          <div style={{ fontSize: "40px", marginBottom: "10px" }}>✓</div>
          <div style={{ color: "var(--muted)", fontSize: "15px" }}>No tasks yet.</div>
          <p style={{ fontSize: "13px", color: "var(--muted)", marginTop: "8px" }}>Add a task or open the Tasks tab — gestation, vaccination, and weaning due soon will appear here automatically.</p>
        </Card>
      )}
    </div>
  );
}
